greeting:
  message: "hello"
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      url: vertx-reactive:postgresql://db:5432/postgres
      
  hibernate-orm:
    database:
      generation: "drop-and-create"





