/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Profile } from './Profile';

export class Article {
    'slug': string;
    'title': string;
    'description': string;
    'body': string;
    'tagList': Array<string>;
    'createdAt': Date;
    'updatedAt': Date;
    'favorited': boolean;
    'favoritesCount': number;
    'author': Profile;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string",
            "format": ""
        },
        {
            "name": "tagList",
            "baseName": "tagList",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "favorited",
            "baseName": "favorited",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "favoritesCount",
            "baseName": "favoritesCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "Profile",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Article.attributeTypeMap;
    }

    public constructor() {
    }
}

