/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenericErrorModelErrors } from './GenericErrorModelErrors';

export class GenericErrorModel {
    'errors': GenericErrorModelErrors;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "GenericErrorModelErrors",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenericErrorModel.attributeTypeMap;
    }

    public constructor() {
    }
}

