/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LoginUser } from './LoginUser';

export class LoginUserRequest {
    'user': LoginUser;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "LoginUser",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoginUserRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

