/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Article } from './Article';

export class MultipleArticlesResponse {
    'articles': Array<Article>;
    'articlesCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "articles",
            "baseName": "articles",
            "type": "Array<Article>",
            "format": ""
        },
        {
            "name": "articlesCount",
            "baseName": "articlesCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultipleArticlesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

