/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NewArticle } from './NewArticle';

export class NewArticleRequest {
    'article': NewArticle;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "article",
            "baseName": "article",
            "type": "NewArticle",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NewArticleRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

