/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NewComment } from './NewComment';

export class NewCommentRequest {
    'comment': NewComment;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "comment",
            "baseName": "comment",
            "type": "NewComment",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NewCommentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

