/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Profile } from './Profile';

export class ProfileResponse {
    'profile': Profile;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "profile",
            "baseName": "profile",
            "type": "Profile",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

