/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Article } from './Article';

export class SingleArticleResponse {
    'article': Article;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "article",
            "baseName": "article",
            "type": "Article",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SingleArticleResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

